id: P007946
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS45274
  title: གསུང་འབུམ། ཚེ་དབང་ནོར་བུ།
  author: ''
  volumes:
    92ee9ec9401b43bf96ac5c027a9b21ac:
      image_group_id: I1GS66283
      title: ''
      volume_number: 1
      total_pages: 908
    cf6c365a11424f12a506bafc327183d0:
      image_group_id: I1GS66284
      title: ''
      volume_number: 2
      total_pages: 754
    bad9a7a1ca544d51bbadb9529e413910:
      image_group_id: I1GS66285
      title: ''
      volume_number: 3
      total_pages: 678
ebook_metadata:
  title: གསུང་འབུམ། ཚེ་དབང་ནོར་བུ།
  author: ''
  sku: P007946
  cover: cover.jpg
  layers:
  - pagination
