id: I636AA6B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:08:49+00:00'
last_modified: '2022-06-09T07:51:08.749118+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS45274
  title: གསུང་འབུམ། ཚེ་དབང་ནོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EED3:
      image_group_id: I1GS66283
      title: Volume 1 of gsung 'bum/_tshe dbang nor bu
      total_pages: 908
      order: 1
      base_file: EED3.txt
    A3AE:
      image_group_id: I1GS66284
      title: Volume 2 of gsung 'bum/_tshe dbang nor bu
      total_pages: 754
      order: 2
      base_file: A3AE.txt
    DB92:
      image_group_id: I1GS66285
      title: Volume 3 of gsung 'bum/_tshe dbang nor bu
      total_pages: 678
      order: 3
      base_file: DB92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
